# Generated by Django 2.0.3 on 2018-04-23 09:09

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180422_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='preview_image',
            field=models.ImageField(null=True, upload_to=myapp.models.post_preview_directory_path),
        ),
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Being taken care of', 'Being taken care of'), ('Hazard eliminated', 'Hazard eliminated')], default='In progress', max_length=30),
        ),
    ]
