# Generated by Django 2.0.2 on 2018-05-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20180423_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyTable',
        ),
        migrations.AddField(
            model_name='posts',
            name='city_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='latitude',
            field=models.CharField(default='37.7214049', max_length=255),
        ),
        migrations.AddField(
            model_name='posts',
            name='longitude',
            field=models.CharField(default='-122.4772705', max_length=255),
        ),
    ]
