# Generated by Django 2.0.3 on 2018-04-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180401_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(null=True, upload_to='posts/%Y/%m/%d'),
        ),
    ]
