# Generated by Django 2.0.3 on 2018-04-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='avatar',
            field=models.ImageField(null=True, upload_to='profile_pictures'),
        ),
    ]
