# Generated by Django 2.0.3 on 2018-04-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180401_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
