# Generated by Django 2.0.2 on 2018-04-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20180423_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyTable',
        ),
    ]
