# Generated by Django 2.0.3 on 2018-05-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_dummytable'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='latitude',
            field=models.CharField(default='37.7214049', max_length=255),
        ),
        migrations.AddField(
            model_name='posts',
            name='longitude',
            field=models.CharField(default='-122.4772705', max_length=255),
        ),
    ]
