# Generated by Django 2.0.3 on 2018-05-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180506_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='location',
        ),
        migrations.AddField(
            model_name='userdata',
            name='city',
            field=models.CharField(default='San Francisco', max_length=255),
        ),
        migrations.AddField(
            model_name='userdata',
            name='state',
            field=models.CharField(default='CA', max_length=255),
        ),
    ]
