# Generated by Django 2.0.3 on 2018-05-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20180517_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='city_official',
            field=models.BooleanField(default=False),
        ),
    ]
